### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by Nidev-lab** [juandurso/PataSana-WEB#13]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Poder ingresar sin problemas.

## Resultado actual

• La pagina no carga.

## Captura

![image](https://github.com/juandurso/PataSana-WEB/assets/53904695/7048d3b7-c17d-4eff-b09e-14416eb03f01)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Nachocastro1** [comment]
Buenas! A nosotros si nos carga la página desde este link:   https://pata-sana-web-git-dev-juandurso.vercel.app/home

**Comment by Nidev-lab** [comment]
Ah bien, deberian cambiar este link chicos.
![image](https://github.com/juandurso/PataSana-WEB/assets/53904695/f6041e1d-ea12-4aa2-ba1a-fb0ca6767343)
