### ISSUE TITLE
Form registro

### ISSUE THREAD

**Issue by Nidev-lab** [juandurso/PataSana-WEB#15]
## Proceso

1. Ingrese a la pagina.
2. Quise registrarme.

## Resultado esperado

• Que no se permitan colocar numeros, signos ni espacios en blancos.

## Resultado actual

• Se pueden colocar numeros, signos y espacios en blancos

## Captura

![image](https://github.com/juandurso/PataSana-WEB/assets/53904695/65964d8f-c4c3-4e5e-8743-49dc4a982975)
![image](https://github.com/juandurso/PataSana-WEB/assets/53904695/ba047d27-23a6-4237-864f-b6068497addd)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Nachocastro1** [comment]
Corregido!
