### ISSUE TITLE
Form contacto

### ISSUE THREAD

**Issue by Nidev-lab** [juandurso/PataSana-WEB#16]
## Proceso

1. Ingrese a la pagina.
2. Quise hacer una consulta.

## Resultado esperado

• Que no se permitan colocar numeros ni signos en el nombre del usuario.
• Que no es permitan colocar solo espacios en el mensaje.
• Que no se mustren mensajes por consola.

## Resultado actual

• Se pueden colocar numeros y letras.
• Se  permite mandar el mensaje con solo espacios.
• Al enviar la consulta se muestra un mensaje por consola.

## Captura

![image](https://github.com/juandurso/PataSana-WEB/assets/53904695/d6c15573-fd86-4662-8817-6ad82bd55647)
![image](https://github.com/juandurso/PataSana-WEB/assets/53904695/0c82e3f4-831f-4553-a6fc-be28db6f66cc)
![image](https://github.com/juandurso/PataSana-WEB/assets/53904695/3f966a5b-182c-4da0-8093-0fd42fe0d952)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Nachocastro1** [comment]
Las correcciones ya fueron aplicadas.
