### ISSUE TITLE
Inicio de sesion

### ISSUE THREAD

**Issue by Nidev-lab** [juandurso/PataSana-WEB#17]
## Proceso

1. Ingrese a la pagina.
2. Me registre con un usuario nuevo.
3. Quise iniciar sesión.

## Resultado esperado

• Poder ingresar sin ningun tipo de problema.

## Resultado actual

• Una vez registrado correctamente no puedo iniciar sesion.

## Captura

![image](https://github.com/juandurso/PataSana-WEB/assets/53904695/03a1b3b2-4aa1-413d-94dc-a54df8c17450)
![image](https://github.com/juandurso/PataSana-WEB/assets/53904695/137fd772-0858-449b-878a-92b6abc928cc)
![image](https://github.com/juandurso/PataSana-WEB/assets/53904695/5e5228eb-3d1f-487f-af0b-49a3f9283707)
![image](https://github.com/juandurso/PataSana-WEB/assets/53904695/2a0132b6-f072-4c12-946c-f42995182df4)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Nachocastro1** [comment]
Buenas noches profe! El unico usuario que puede acceder es el admin, ya que era un requisito opcional. Agregamos un alert que notifique que por el momento no es posible registrarse.

**Comment by Nachocastro1** [comment]
![image](https://github.com/juandurso/PataSana-WEB/assets/126210288/1e03fbe2-2571-4f1e-80e5-d8b960bfcadd)
