### ISSUE TITLE
Boton sin accion

### ISSUE THREAD

**Issue by Nidev-lab** [juandurso/PataSana-WEB#18]
## Proceso

1. Ingrese a la pagina.
2. Quise contratar un plan.

## Resultado esperado

• Que al hacer click en el botón "Sumar servicios" obtener información de como obtener el servicio o redirigir a una page 404.

## Resultado actual

• El boton "Sumar servicios" no cumple ninguna funcion.

## Captura

![image](https://github.com/juandurso/PataSana-WEB/assets/53904695/4725b685-d0dc-40b7-bc3d-8923f4b3bf7f)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by juandurso** [comment]
boton (sumar servicios) tiene funcionalidad, lo agrega al carrito que se encuentra en la parte superior para comprar el servicio deseado.

**Comment by Nidev-lab** [comment]
Deberían incluir un modal o algo que avise que se agrego al carrito, ya que no hay nada que te informe que se agrego al carrito el servicio solicitado

**Comment by Nachocastro1** [comment]
Buenas noches profe! Agregamos un alert que avisa que el producto fue añadido al carrito.
