### ISSUE TITLE
Imagen sin carga

### ISSUE THREAD

**Issue by Nidev-lab** [juandurso/PataSana-WEB#19]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que las imágenes de la pagina se encuentren correctamente.

## Resultado actual

• Se encuentran imágenes sin cargar.

## Captura

![image](https://github.com/juandurso/PataSana-WEB/assets/53904695/f5b0c4c8-0b42-43f0-bbc7-b72080f8caae)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Nidev-lab** [comment]
Buenas! Chicos para seguir con la devolución del proyecto necesitaría un usuario admin, me podrían dejar uno comentado abajo o pasármelo por slack? Gracias!

**Comment by Nachocastro1** [comment]
Profe! Acá tiene que aceptar la ubicacion a mi despues de aceptar la ubicacion me salen las animaciones y la informacion

**Comment by Nachocastro1** [comment]
![image](https://github.com/juandurso/PataSana-WEB/assets/126210288/207f72d0-791b-4914-babd-ad9a856f136b)
